version: '3'

services:
  main-module:
    build: main-module
    container_name: main-module-app
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005