spring:
  profiles:
    active: local
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ssZ"
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      base-path: /private
      exposure.include: health,info
  info:
    java:
      enabled: true

springdoc:
  api-docs:
    path: /openapi


kafka:
  bootstrapAddress: http://localhost:29092