management:
  endpoints:
    web:
      base-path: /private
      exposure.include: info, health, status, prometheus

ovp:
  logging:
    encryptionFields:
      MVPD_DATA_HEADER: ${MVPD_DATA_HEADER_ENCRYPTION_KEY:abc}
      OAT: ${OAT_LOGGING_ENCRYPTION_KEY:abc}
      SYNACOR_CLOUD_ACCOUNT_ID: ${SYNACOR_CLOUD_ACCOUNT_ID_ENCRYPTION_KEY:abc}